### ISSUE TITLE
Does total_workers value increase upon worker connection?

### ISSUE THREAD

**Issue by fsiddi** [fsiddi/brender#72]
When a Worker connects to the Manager, does the count of total_workers change?

**Comment by msimoncz** [comment]
Maybe a better things to do: implementing a property in Manager class which count the available workers connected to it.

**Comment by fsiddi** [comment]
I'm working on this. In order to improve manager vs. server communication, I propose to introduce a hashed ID, that gets stored into the manager setting upon initial registration with the server, as well as on the server in the manager table. The following times the manager needs to connect to the server, it can identify itself as a resource by using such ID.

**Comment by fsiddi** [comment]
Addressed in a8c4e36176abc7b8d452f57255140f261c1c76d4.
