### ISSUE TITLE
Enabing / Disabling Wokers don't work

### ISSUE THREAD

**Issue by Eibriel** [fsiddi/brender#87]
Enabing / Disabling Wokers don't work

**Comment by Eibriel** [comment]
Needs further investigation.
How I know to which Manager ask to change Worker status?

**Comment by msimoncz** [comment]
Nowadays, there is no way to get it through the database. But, here is my idea: when you get all the workers from the dashboard, you can add a manager_id field, get it and store it as `<hidden>` in the form and then, when you send a "Enable/Disable" you send the order to the worker (with manager_id) so you know to which manager you should send the request. Does it make sense?

**Comment by fsiddi** [comment]
I've discussed this with @Eibriel today, and I'm going to take care of it, probably tomorrow. Your proposal sounds fine. We will basically happend on the fly the manager id to each worker resource.

**Comment by Eibriel** [comment]
Fixed with https://github.com/fsiddi/brender/commit/d13562d4cf2f3e579c66e0c5925952c4187f43d2 https://github.com/fsiddi/brender/commit/a07f8466acab12180b0f311460e66305faabd0ea https://github.com/fsiddi/brender/commit/ad230bba54581b592270296d1246e1fb0284372e
